// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "naivete/internal/logic/graph"
	_ "naivete/internal/logic/page"
)
