// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IGraph interface {
	BuildGraph(ctx context.Context) error
	Create(ctx context.Context, nodeName string, params map[string]any) (any, error)
	ExecuteCql(ctx context.Context, cql string) (any, error)
	Create_relationship(ctx context.Context, start_node string, end_node, pname string, edges []string, rel_type, rel_name string) error
}

var localGraph IGraph

func Graph() IGraph {
	if localGraph == nil {
		panic("implement not found for interface IGraph, forgot register?")
	}
	return localGraph
}

func RegisterGraph(i IGraph) {
	localGraph = i
}
