// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IPage interface {
	Create(ctx context.Context, wd string) (err error)
}

var localPage IPage

func Page() IPage {
	if localPage == nil {
		panic("implement not found for interface IPage, forgot register?")
	}
	return localPage
}

func RegisterPage(i IPage) {
	localPage = i
}
